// ZIVO — script.js
// Auto-generated by scripts/generate.py. Edit CELEBRITIES there, not here.

const CELEBRITIES = [
  {
    "id": "tom-holland",
    "name": "Tom Holland",
    "category": "actors",
    "categoryLabel": "Actors",
    "role": "Actor",
    "initials": "TH",
    "color": "#7A3B3B",
    "catalogNo": "N° 001",
    "url": "profiles/tom-holland.html",
    "summary": "Tom Holland is an English actor best known for playing Spider-Man in the Marvel Cinematic Universe, following a path that began in London musical theatre."
  },
  {
    "id": "zendaya",
    "name": "Zendaya",
    "category": "actors",
    "categoryLabel": "Actors",
    "role": "Actress & Producer",
    "initials": "ZZ",
    "color": "#7A3B3B",
    "catalogNo": "N° 002",
    "url": "profiles/zendaya.html",
    "summary": "Zendaya is an American actress and producer who moved from Disney Channel comedy into critically acclaimed drama, becoming the youngest actress to win two Primetime Emmy Awards for Outstanding Lead Actress."
  },
  {
    "id": "taylor-swift",
    "name": "Taylor Swift",
    "category": "singers",
    "categoryLabel": "Singers",
    "role": "Singer-Songwriter",
    "initials": "TS",
    "color": "#3E4C78",
    "catalogNo": "N° 003",
    "url": "profiles/taylor-swift.html",
    "summary": "Taylor Swift is an American singer-songwriter who began in country music before becoming one of the best-selling and most influential artists in pop music history."
  },
  {
    "id": "ed-sheeran",
    "name": "Ed Sheeran",
    "category": "singers",
    "categoryLabel": "Singers",
    "role": "Singer-Songwriter",
    "initials": "ES",
    "color": "#3E4C78",
    "catalogNo": "N° 004",
    "url": "profiles/ed-sheeran.html",
    "summary": "Ed Sheeran is a British singer-songwriter known for genre-blending, acoustic-rooted pop, and one of the best-selling music artists of the 21st century."
  },
  {
    "id": "cristiano-ronaldo",
    "name": "Cristiano Ronaldo",
    "category": "athletes",
    "categoryLabel": "Athletes",
    "role": "Professional Footballer (Forward)",
    "initials": "CR",
    "color": "#386B4C",
    "catalogNo": "N° 005",
    "url": "profiles/cristiano-ronaldo.html",
    "summary": "Cristiano Ronaldo is a Portuguese professional footballer widely regarded as one of the greatest players in the sport's history, known for goal-scoring records built across four countries and more than two decades."
  },
  {
    "id": "lionel-messi",
    "name": "Lionel Messi",
    "category": "athletes",
    "categoryLabel": "Athletes",
    "role": "Professional Footballer (Forward)",
    "initials": "LM",
    "color": "#386B4C",
    "catalogNo": "N° 006",
    "url": "profiles/lionel-messi.html",
    "summary": "Lionel Messi is an Argentine professional footballer widely regarded as one of the greatest players of all time, holder of a record eight Ballon d'Or awards and a 2022 FIFA World Cup winner with Argentina."
  },
  {
    "id": "mrbeast",
    "name": "MrBeast",
    "category": "creators",
    "categoryLabel": "Creators",
    "role": "Content Creator, Entrepreneur & Philanthropist",
    "initials": "MM",
    "color": "#2E6B72",
    "catalogNo": "N° 007",
    "url": "profiles/mrbeast.html",
    "summary": "MrBeast, the online name of Jimmy Donaldson, is an American YouTuber and entrepreneur known for elaborate, high-budget challenge videos and large-scale philanthropic giveaways, and is the most-subscribed individual creator on the platform."
  },
  {
    "id": "pewdiepie",
    "name": "PewDiePie",
    "category": "creators",
    "categoryLabel": "Creators",
    "role": "Content Creator",
    "initials": "PP",
    "color": "#2E6B72",
    "catalogNo": "N° 008",
    "url": "profiles/pewdiepie.html",
    "summary": "PewDiePie, the online name of Felix Kjellberg, is a Swedish YouTuber and one of the earliest individual creators to build a global audience, widely credited with helping popularize gaming commentary videos as a format."
  },
  {
    "id": "bill-gates",
    "name": "Bill Gates",
    "category": "entrepreneurs",
    "categoryLabel": "Entrepreneurs",
    "role": "Entrepreneur, Philanthropist & Author",
    "initials": "BG",
    "color": "#7A5C2E",
    "catalogNo": "N° 009",
    "url": "profiles/bill-gates.html",
    "summary": "Bill Gates is an American entrepreneur and philanthropist who co-founded Microsoft Corporation and helped drive the personal-computer revolution, before shifting his focus to global health and education through the Gates Foundation."
  },
  {
    "id": "sara-blakely",
    "name": "Sara Blakely",
    "category": "entrepreneurs",
    "categoryLabel": "Entrepreneurs",
    "role": "Entrepreneur & Founder",
    "initials": "SB",
    "color": "#7A5C2E",
    "catalogNo": "N° 010",
    "url": "profiles/sara-blakely.html",
    "summary": "Sara Blakely is an American entrepreneur who invented and founded Spanx, becoming, in 2012, the youngest self-made female billionaire on record."
  }
];

/* ---------- shared site behavior ---------- */
(function () {
  "use strict";
  document.addEventListener("DOMContentLoaded", function () {
    initHeaderScroll(); initMobileNav(); initHeaderSearchToggle();
    initAutocomplete(); initAgeFields(); initYearFields();
    initFileIndexScrollSpy(); initContactForm();
  });

  function initHeaderScroll() {
    var header = document.querySelector(".site-header");
    if (!header) return;
    function onScroll() { header.classList.toggle("is-scrolled", window.scrollY > 8); }
    window.addEventListener("scroll", onScroll, { passive: true }); onScroll();
  }

  function initMobileNav() {
    var toggle = document.querySelector(".menu-toggle"), nav = document.querySelector(".mobile-nav"),
        close = document.querySelector(".mobile-nav__close");
    if (!toggle || !nav) return;
    function open() { nav.classList.add("is-open"); nav.setAttribute("aria-hidden", "false"); document.body.style.overflow = "hidden"; toggle.setAttribute("aria-expanded", "true"); }
    function shut() { nav.classList.remove("is-open"); nav.setAttribute("aria-hidden", "true"); document.body.style.overflow = ""; toggle.setAttribute("aria-expanded", "false"); }
    toggle.addEventListener("click", open);
    if (close) close.addEventListener("click", shut);
    nav.querySelectorAll(".mobile-nav__link").forEach(function (l) { l.addEventListener("click", shut); });
    document.addEventListener("keydown", function (e) { if (e.key === "Escape") shut(); });
  }

  function initHeaderSearchToggle() {
    var toggle = document.querySelector(".search-toggle"), bar = document.querySelector(".header-search");
    if (!toggle || !bar) return;
    var input = bar.querySelector(".header-search__input");
    toggle.addEventListener("click", function () {
      var isOpen = bar.classList.toggle("is-open");
      toggle.setAttribute("aria-expanded", isOpen ? "true" : "false");
      if (isOpen && input) setTimeout(function () { input.focus(); }, 150);
    });
    document.addEventListener("keydown", function (e) {
      if (e.key === "Escape" && bar.classList.contains("is-open")) { bar.classList.remove("is-open"); toggle.setAttribute("aria-expanded", "false"); }
    });
  }

  function initAutocomplete() {
    var forms = document.querySelectorAll("[data-search-autocomplete]");
    if (!forms.length || typeof CELEBRITIES === "undefined") return;
    forms.forEach(function (form) {
      var input = form.querySelector("input[type='search'], input[type='text']"), box = form.querySelector(".search-suggestions");
      if (!input || !box) return;
      var items = [], activeIndex = -1;
      function render(query) {
        var q = query.trim().toLowerCase(); box.innerHTML = ""; items = []; activeIndex = -1;
        if (!q) { box.classList.remove("is-open"); return; }
        var matches = CELEBRITIES.filter(function (c) { return c.name.toLowerCase().indexOf(q) !== -1; }).slice(0, 6);
        if (!matches.length) {
          var empty = document.createElement("div"); empty.className = "suggestion__empty";
          empty.textContent = "No profiles match \u201c" + query + "\u201d"; box.appendChild(empty); box.classList.add("is-open"); return;
        }
        matches.forEach(function (c) {
          var a = document.createElement("a"); a.className = "suggestion"; a.href = c.url; a.setAttribute("role", "option");
          var photo = document.createElement("span"); photo.className = "suggestion__photo"; photo.style.background = c.color; photo.textContent = c.initials;
          var meta = document.createElement("span");
          var nameEl = document.createElement("span"); nameEl.className = "suggestion__name"; nameEl.textContent = c.name;
          var metaEl = document.createElement("span"); metaEl.className = "suggestion__meta"; metaEl.textContent = c.role + " \u00b7 " + c.categoryLabel;
          meta.appendChild(nameEl); meta.appendChild(document.createElement("br")); meta.appendChild(metaEl);
          a.appendChild(photo); a.appendChild(meta); box.appendChild(a); items.push(a);
        });
        box.classList.add("is-open");
      }
      function setActive(i) {
        items.forEach(function (el) { el.classList.remove("is-focused"); });
        if (items[i]) { items[i].classList.add("is-focused"); items[i].scrollIntoView({ block: "nearest" }); }
        activeIndex = i;
      }
      input.addEventListener("input", function () { render(input.value); });
      input.addEventListener("focus", function () { if (input.value.trim()) render(input.value); });
      input.addEventListener("keydown", function (e) {
        if (!box.classList.contains("is-open") || !items.length) return;
        if (e.key === "ArrowDown") { e.preventDefault(); setActive(Math.min(activeIndex + 1, items.length - 1)); }
        else if (e.key === "ArrowUp") { e.preventDefault(); setActive(Math.max(activeIndex - 1, 0)); }
        else if (e.key === "Enter" && activeIndex > -1) { e.preventDefault(); items[activeIndex].click(); }
        else if (e.key === "Escape") { box.classList.remove("is-open"); }
      });
      document.addEventListener("click", function (e) { if (!form.contains(e.target)) box.classList.remove("is-open"); });
    });
  }

  function initAgeFields() {
    document.querySelectorAll("[data-birthdate]").forEach(function (el) {
      var bd = el.getAttribute("data-birthdate"); if (!bd) return;
      var birth = new Date(bd + "T00:00:00"); if (isNaN(birth.getTime())) return;
      var today = new Date(); var age = today.getFullYear() - birth.getFullYear();
      var m = today.getMonth() - birth.getMonth();
      if (m < 0 || (m === 0 && today.getDate() < birth.getDate())) age--;
      el.textContent = age;
    });
  }

  function initYearFields() {
    document.querySelectorAll("[data-year]").forEach(function (el) { el.textContent = new Date().getFullYear(); });
  }

  function initFileIndexScrollSpy() {
    var nav = document.querySelector(".file-index"); if (!nav || !("IntersectionObserver" in window)) return;
    var links = Array.prototype.slice.call(nav.querySelectorAll(".file-index__link"));
    var sections = links.map(function (l) { return document.getElementById(l.getAttribute("href").replace("#", "")); }).filter(Boolean);
    if (!sections.length) return;
    var observer = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (!entry.isIntersecting) return;
        var link = nav.querySelector('.file-index__link[href="#' + entry.target.id + '"]'); if (!link) return;
        links.forEach(function (l) { l.classList.remove("is-active"); }); link.classList.add("is-active");
      });
    }, { rootMargin: "-140px 0px -60% 0px", threshold: 0.01 });
    sections.forEach(function (s) { observer.observe(s); });
  }

  function initContactForm() {
    var form = document.querySelector(".contact-form"); if (!form) return;
    var success = form.querySelector(".form-success");
    form.addEventListener("submit", function (e) {
      e.preventDefault();
      if (!form.checkValidity()) { form.reportValidity(); return; }
      var btn = form.querySelector("button[type='submit']");
      if (btn) { btn.disabled = true; btn.textContent = "Sending\u2026"; }
      setTimeout(function () {
        if (success) success.classList.add("is-visible");
        form.reset();
        if (btn) { btn.disabled = false; btn.textContent = "Send Message"; }
      }, 600);
    });
  }
})();

/* ---------- search results page (search.html only) ---------- */
(function () {
  "use strict";
  document.addEventListener("DOMContentLoaded", function () {
    var grid = document.getElementById("resultsGrid"), metaEl = document.getElementById("searchMeta"),
        emptyState = document.getElementById("emptyState"), input = document.getElementById("searchPageInput"),
        form = document.getElementById("searchPageForm");
    if (!grid || typeof CELEBRITIES === "undefined") return;

    var params = new URLSearchParams(window.location.search);
    var initialQuery = (params.get("q") || "").trim();
    if (input) input.value = initialQuery;
    renderResults(initialQuery);

    if (form) {
      form.addEventListener("submit", function (e) {
        e.preventDefault();
        var q = input ? input.value.trim() : "";
        var url = new URL(window.location.href);
        if (q) url.searchParams.set("q", q); else url.searchParams.delete("q");
        window.history.pushState({}, "", url);
        renderResults(q);
      });
    }

    function renderResults(query) {
      var q = query.trim().toLowerCase();
      grid.innerHTML = "";
      if (!q) { if (metaEl) metaEl.textContent = "Enter a name above to search the archive."; if (emptyState) emptyState.style.display = "none"; return; }
      var results = CELEBRITIES.filter(function (c) {
        return c.name.toLowerCase().indexOf(q) !== -1 || c.role.toLowerCase().indexOf(q) !== -1 || c.categoryLabel.toLowerCase().indexOf(q) !== -1;
      });
      if (metaEl) {
        metaEl.innerHTML = results.length
          ? "<strong>" + results.length + "</strong> result" + (results.length === 1 ? "" : "s") + " for \u201c" + escapeHtml(query) + "\u201d"
          : "No results for \u201c" + escapeHtml(query) + "\u201d";
      }
      if (!results.length) { if (emptyState) emptyState.style.display = "block"; return; }
      if (emptyState) emptyState.style.display = "none";
      results.forEach(function (c) { grid.appendChild(buildCard(c)); });
    }

    function buildCard(c) {
      var a = document.createElement("a"); a.href = c.url; a.className = "file-card";
      a.innerHTML =
        '<div class="file-card__top"><div class="id-photo" style="--accent:' + c.color + '">' + escapeHtml(c.initials) + '</div>' +
        '<div class="file-card__id"><span class="catalog-no file-card__catalog">' + escapeHtml(c.catalogNo) + '</span>' +
        '<h3 class="file-card__name">' + escapeHtml(c.name) + '</h3><p class="file-card__role">' + escapeHtml(c.role) + '</p></div></div>' +
        '<div class="file-card__body"><p class="file-card__blurb">' + escapeHtml(c.summary) + '</p>' +
        '<div class="file-card__foot"><span class="tag" style="--accent:' + c.color + '">' + escapeHtml(c.categoryLabel) + '</span>' +
        '<span class="file-card__link">View Profile</span></div></div>';
      return a;
    }
    function escapeHtml(str) { var div = document.createElement("div"); div.textContent = str; return div.innerHTML; }
  });
})();
